#!/bin/bash

# Agent Execution Script
# Generated by execute-with-agents.js

# Execute: lucy: Home Builder Helper: Concept & wireframes
sessions_spawn \
  --task "
=== EXECUTE THIS BRIEFING ===

TASK: Home Builder Helper: Concept & wireframes
PRIORITY: High
AGENT: LUCY
DUE: 2026-04-06
ESTIMATE: 4 hours

=== BRIEFING ===

Project: Home Builder Helper
Task: Concept & wireframes
Details: Create design concepts and wireframes
Timeline: TBD
Owner: Lucy

Goals: See project details

This is a Level 2 task for \"Home Builder Helper\".
✅ Execute immediately.

=== EXECUTION RULES ===

1. **AUTONOMY LEVEL 2** — Execute immediately, no approval needed
2. **AI SPEED** — Target 4h completion with parallelization
3. **QUALITY** — Deliver production-ready work
4. **DOCUMENTATION** — Log key decisions and progress
5. **COMPLETION SIGNAL** — End with [TASK_COMPLETE] when done

=== COMPLETION SIGNAL (REQUIRED) ===

When task is complete, include this at the end of your response:

[TASK_COMPLETE] taskId: 17748873898619ufqhfbud

This signals the system to:
✓ Auto-update task status to \"complete\"
✓ Mark project progress
✓ Trigger downstream work

DO NOT FORGET THIS SIGNAL.

=== YOUR CONTEXT ===

You are lucy, a specialist in your domain.
This is your type of work. Execute with full confidence and autonomy.
You don't need to ask permission or wait for approval.

Model: minimax/MiniMax-M2.5
Focus: Execute this task with excellence.
Goal: Complete this work at AI speed (hours, not days).

Good luck! 🚀
" \
  --agentId lucy \
  --mode run \
  --runtime subagent \
  --timeoutSeconds 14400

# Execute: lucy: Home Builder Helper: High-fidelity design
sessions_spawn \
  --task "
=== EXECUTE THIS BRIEFING ===

TASK: Home Builder Helper: High-fidelity design
PRIORITY: High
AGENT: LUCY
DUE: 2026-04-06
ESTIMATE: 4 hours

=== BRIEFING ===

Project: Home Builder Helper
Task: High-fidelity design
Details: Develop high-fidelity mockups
Timeline: TBD
Owner: Lucy

Goals: See project details

This is a Level 2 task for \"Home Builder Helper\".
✅ Execute immediately.

=== EXECUTION RULES ===

1. **AUTONOMY LEVEL 2** — Execute immediately, no approval needed
2. **AI SPEED** — Target 4h completion with parallelization
3. **QUALITY** — Deliver production-ready work
4. **DOCUMENTATION** — Log key decisions and progress
5. **COMPLETION SIGNAL** — End with [TASK_COMPLETE] when done

=== COMPLETION SIGNAL (REQUIRED) ===

When task is complete, include this at the end of your response:

[TASK_COMPLETE] taskId: 17748873898619fl96p1qb

This signals the system to:
✓ Auto-update task status to \"complete\"
✓ Mark project progress
✓ Trigger downstream work

DO NOT FORGET THIS SIGNAL.

=== YOUR CONTEXT ===

You are lucy, a specialist in your domain.
This is your type of work. Execute with full confidence and autonomy.
You don't need to ask permission or wait for approval.

Model: minimax/MiniMax-M2.5
Focus: Execute this task with excellence.
Goal: Complete this work at AI speed (hours, not days).

Good luck! 🚀
" \
  --agentId lucy \
  --mode run \
  --runtime subagent \
  --timeoutSeconds 14400

# Execute: lucy: Home Builder Helper: Design system
sessions_spawn \
  --task "
=== EXECUTE THIS BRIEFING ===

TASK: Home Builder Helper: Design system
PRIORITY: High
AGENT: LUCY
DUE: 2026-04-06
ESTIMATE: 4 hours

=== BRIEFING ===

Project: Home Builder Helper
Task: Design system
Details: Create design system and components
Timeline: TBD
Owner: Lucy

Goals: See project details

This is a Level 2 task for \"Home Builder Helper\".
✅ Execute immediately.

=== EXECUTION RULES ===

1. **AUTONOMY LEVEL 2** — Execute immediately, no approval needed
2. **AI SPEED** — Target 4h completion with parallelization
3. **QUALITY** — Deliver production-ready work
4. **DOCUMENTATION** — Log key decisions and progress
5. **COMPLETION SIGNAL** — End with [TASK_COMPLETE] when done

=== COMPLETION SIGNAL (REQUIRED) ===

When task is complete, include this at the end of your response:

[TASK_COMPLETE] taskId: 1774887389861trgykfgl1

This signals the system to:
✓ Auto-update task status to \"complete\"
✓ Mark project progress
✓ Trigger downstream work

DO NOT FORGET THIS SIGNAL.

=== YOUR CONTEXT ===

You are lucy, a specialist in your domain.
This is your type of work. Execute with full confidence and autonomy.
You don't need to ask permission or wait for approval.

Model: minimax/MiniMax-M2.5
Focus: Execute this task with excellence.
Goal: Complete this work at AI speed (hours, not days).

Good luck! 🚀
" \
  --agentId lucy \
  --mode run \
  --runtime subagent \
  --timeoutSeconds 14400

# Execute: lucy: Home Builder Helper: Handoff & specs
sessions_spawn \
  --task "
=== EXECUTE THIS BRIEFING ===

TASK: Home Builder Helper: Handoff & specs
PRIORITY: High
AGENT: LUCY
DUE: 2026-04-06
ESTIMATE: 4 hours

=== BRIEFING ===

Project: Home Builder Helper
Task: Handoff & specs
Details: Prepare specs for development
Timeline: TBD
Owner: Lucy

Goals: See project details

This is a Level 2 task for \"Home Builder Helper\".
✅ Execute immediately.

=== EXECUTION RULES ===

1. **AUTONOMY LEVEL 2** — Execute immediately, no approval needed
2. **AI SPEED** — Target 4h completion with parallelization
3. **QUALITY** — Deliver production-ready work
4. **DOCUMENTATION** — Log key decisions and progress
5. **COMPLETION SIGNAL** — End with [TASK_COMPLETE] when done

=== COMPLETION SIGNAL (REQUIRED) ===

When task is complete, include this at the end of your response:

[TASK_COMPLETE] taskId: 1774887389861l617ovqw3

This signals the system to:
✓ Auto-update task status to \"complete\"
✓ Mark project progress
✓ Trigger downstream work

DO NOT FORGET THIS SIGNAL.

=== YOUR CONTEXT ===

You are lucy, a specialist in your domain.
This is your type of work. Execute with full confidence and autonomy.
You don't need to ask permission or wait for approval.

Model: minimax/MiniMax-M2.5
Focus: Execute this task with excellence.
Goal: Complete this work at AI speed (hours, not days).

Good luck! 🚀
" \
  --agentId lucy \
  --mode run \
  --runtime subagent \
  --timeoutSeconds 14400

# Execute: lucy: Home Builder Helper: Validation & iteration
sessions_spawn \
  --task "
=== EXECUTE THIS BRIEFING ===

TASK: Home Builder Helper: Validation & iteration
PRIORITY: High
AGENT: LUCY
DUE: 2026-04-06
ESTIMATE: 4 hours

=== BRIEFING ===

Project: Home Builder Helper
Task: Validation & iteration
Details: Test with users and iterate
Timeline: TBD
Owner: Lucy

Goals: See project details

This is a Level 2 task for \"Home Builder Helper\".
✅ Execute immediately.

=== EXECUTION RULES ===

1. **AUTONOMY LEVEL 2** — Execute immediately, no approval needed
2. **AI SPEED** — Target 4h completion with parallelization
3. **QUALITY** — Deliver production-ready work
4. **DOCUMENTATION** — Log key decisions and progress
5. **COMPLETION SIGNAL** — End with [TASK_COMPLETE] when done

=== COMPLETION SIGNAL (REQUIRED) ===

When task is complete, include this at the end of your response:

[TASK_COMPLETE] taskId: 1774887389862yitvf0xzl

This signals the system to:
✓ Auto-update task status to \"complete\"
✓ Mark project progress
✓ Trigger downstream work

DO NOT FORGET THIS SIGNAL.

=== YOUR CONTEXT ===

You are lucy, a specialist in your domain.
This is your type of work. Execute with full confidence and autonomy.
You don't need to ask permission or wait for approval.

Model: minimax/MiniMax-M2.5
Focus: Execute this task with excellence.
Goal: Complete this work at AI speed (hours, not days).

Good luck! 🚀
" \
  --agentId lucy \
  --mode run \
  --runtime subagent \
  --timeoutSeconds 14400

# Execute: johnny: Test: Collaboration Features: Architecture & Planning
sessions_spawn \
  --task "
=== EXECUTE THIS BRIEFING ===

TASK: Test: Collaboration Features: Architecture & Planning
PRIORITY: High
AGENT: JOHNNY
DUE: 2026-04-06
ESTIMATE: 40 hours

=== BRIEFING ===

Development phase 1: Design system architecture and technical specifications

=== EXECUTION RULES ===

1. **AUTONOMY LEVEL 2** — Execute immediately, no approval needed
2. **AI SPEED** — Target 40h completion with parallelization
3. **QUALITY** — Deliver production-ready work
4. **DOCUMENTATION** — Log key decisions and progress
5. **COMPLETION SIGNAL** — End with [TASK_COMPLETE] when done

=== COMPLETION SIGNAL (REQUIRED) ===

When task is complete, include this at the end of your response:

[TASK_COMPLETE] taskId: 1774888743175

This signals the system to:
✓ Auto-update task status to \"complete\"
✓ Mark project progress
✓ Trigger downstream work

DO NOT FORGET THIS SIGNAL.

=== YOUR CONTEXT ===

You are johnny, a specialist in your domain.
This is your type of work. Execute with full confidence and autonomy.
You don't need to ask permission or wait for approval.

Model: minimax/MiniMax-M2.5
Focus: Execute this task with excellence.
Goal: Complete this work at AI speed (hours, not days).

Good luck! 🚀
" \
  --agentId johnny \
  --mode run \
  --runtime subagent \
  --timeoutSeconds 14400

# Execute: johnny: Home Builder Helper: Discovery & Planning
sessions_spawn \
  --task "
=== EXECUTE THIS BRIEFING ===

TASK: Home Builder Helper: Discovery & Planning
PRIORITY: High
AGENT: JOHNNY
DUE: 2026-04-06
ESTIMATE: 40 hours

=== BRIEFING ===

Product phase 1: Requirements gathering, user research, and feature prioritization

=== EXECUTION RULES ===

1. **AUTONOMY LEVEL 2** — Execute immediately, no approval needed
2. **AI SPEED** — Target 40h completion with parallelization
3. **QUALITY** — Deliver production-ready work
4. **DOCUMENTATION** — Log key decisions and progress
5. **COMPLETION SIGNAL** — End with [TASK_COMPLETE] when done

=== COMPLETION SIGNAL (REQUIRED) ===

When task is complete, include this at the end of your response:

[TASK_COMPLETE] taskId: 1774898595135

This signals the system to:
✓ Auto-update task status to \"complete\"
✓ Mark project progress
✓ Trigger downstream work

DO NOT FORGET THIS SIGNAL.

=== YOUR CONTEXT ===

You are johnny, a specialist in your domain.
This is your type of work. Execute with full confidence and autonomy.
You don't need to ask permission or wait for approval.

Model: minimax/MiniMax-M2.5
Focus: Execute this task with excellence.
Goal: Complete this work at AI speed (hours, not days).

Good luck! 🚀
" \
  --agentId johnny \
  --mode run \
  --runtime subagent \
  --timeoutSeconds 14400

