const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

// Generate PDF for completed JTSA
const generateJTSAPdf = async (jtsa, company, project, hazards, mitigations) => {
  return new Promise((resolve, reject) => {
    try {
      const filename = `JTSA_${jtsa.id}_${jtsa.date}.pdf`;
      const filepath = path.join(__dirname, '../../pdfs', filename);

      // Ensure pdfs directory exists
      const pdfDir = path.dirname(filepath);
      if (!fs.existsSync(pdfDir)) {
        fs.mkdirSync(pdfDir, { recursive: true });
      }

      const doc = new PDFDocument({
        size: 'letter',
        margin: 50,
      });

      const stream = fs.createWriteStream(filepath);
      doc.pipe(stream);

      // Header
      doc.fontSize(20).font('Helvetica-Bold').text('Job Task Safety Analysis (JTSA)', { align: 'center' });
      doc.fontSize(10).font('Helvetica').text(`Generated: ${new Date().toLocaleString()}`, { align: 'center' });
      doc.moveDown();

      // Company & Project Info
      doc.fontSize(12).font('Helvetica-Bold').text('Company Information');
      doc.fontSize(10).font('Helvetica')
        .text(`Company: ${company.name}`)
        .text(`Project: ${project.name}`)
        .text(`Date: ${jtsa.date}`)
        .text(`JTSA ID: ${jtsa.id}`);
      doc.moveDown();

      // Task Description
      doc.fontSize(12).font('Helvetica-Bold').text('Task Description');
      doc.fontSize(10).font('Helvetica').text(jtsa.task_description, { align: 'left', width: 450 });
      doc.moveDown();

      // Hazards Section
      doc.fontSize(12).font('Helvetica-Bold').text('Identified Hazards');
      if (hazards && hazards.length > 0) {
        hazards.forEach((hazard, index) => {
          doc.fontSize(10).font('Helvetica-Bold')
            .text(`${index + 1}. ${hazard.description}`, { width: 450 });
          doc.fontSize(9).font('Helvetica')
            .text(`Severity: ${hazard.severity}`)
            .text(`Acknowledged: ${hazard.user_acknowledged ? 'Yes' : 'No'}`)
            .text(`AI Suggested: ${hazard.ai_suggested ? 'Yes' : 'No'}`);
          
          // Mitigations for this hazard
          const hazardMitigations = mitigations?.filter(m => m.hazard_id === hazard.id) || [];
          if (hazardMitigations.length > 0) {
            doc.fontSize(9).font('Helvetica-Bold').text('Mitigation Plans:');
            hazardMitigations.forEach((mit, mitIndex) => {
              doc.fontSize(8).font('Helvetica')
                .text(`${mitIndex + 1}. ${mit.mitigation_plan}`)
                .text(`Accepted: ${mit.user_accepted ? 'Yes' : 'No'}`)
                .text(`AI Feedback: ${mit.ai_feedback || 'Pending'}`)
                .text('');
            });
          }
          doc.moveDown();
        });
      } else {
        doc.fontSize(10).font('Helvetica').text('No hazards identified');
        doc.moveDown();
      }

      // Footer
      doc.fontSize(8).font('Helvetica').text('This document is provided for OSHA compliance and workplace safety purposes.', { align: 'center' });
      doc.text(`Generated by JTSA Tool - ${new Date().getFullYear()}`, { align: 'center' });

      doc.end();

      stream.on('finish', () => {
        resolve(filepath);
      });

      stream.on('error', (err) => {
        reject(err);
      });
    } catch (error) {
      reject(error);
    }
  });
};

module.exports = {
  generateJTSAPdf,
};
